LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := dtbtool_moto
LOCAL_SRC_FILES := dtbtool.c
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_SUFFIX := $(HOST_EXECUTABLE_SUFFIX)
include $(BUILD_HOST_EXECUTABLE)
